### ISSUE TITLE
Is there an updated link somehwere else to the dataset

### ISSUE THREAD

**Issue by astroC86** [wdqin/BE-Arabic-9K#1]

**Comment by hritikiiti** [comment]
link not working not even on http

**Comment by ghassenBtb** [comment]
Same, it would be great if we can get an updated url to the dataset

**Comment by wdqin** [comment]
Hi all,

The new download link is updated. If you are still interested in the dataset, you might want to check it out. Please let me know if the anything is needed in the dataset is missing, I will take a look and let you know if I can do anything about that. I am talking to my department for a better place to store the data in the long run, so I might need to update the download link in the near future.

As for the dataset and the code, since everything is done many years ago so I can't guarantee the code still works nowadays, but still, feel free to let me know and I will check if there's anything I can do.

I apologize for the missing data for such a long time.

-Wenda

**Comment by ghassenBtb** [comment]
Thank you very much, this is helpful.
I checked, and I have indeed access to the unlabeled pdfs of scanned arabic documents.

However, it is mentioned in the README that the data consists also of labeled data somewhere in folders and csv file named data/ and data_info.csv.
Do you have any information about that ?
It would be great if we can get access to labeled data :) 
PS: By labeled I mean the correctly extracted text from pdfs.

**Comment by wdqin** [comment]
I think I also put the data/ and data_info.csv in the Drive. They are just not in the "**-unlabeled/" folders but within the same directory. You should probably double check.

**Comment by ghassenBtb** [comment]
The link you shared is only for the **-unlabeled/ folder, and inside the folder I only see pdfs/ and 2 other files.
![image](https://github.com/wdqin/BE-Arabic-9K/assets/58640352/4b249bb2-27ce-422f-839a-6b538992847a)

**Comment by wdqin** [comment]
Thanks for showing the screenshot. Can you try again? This time it should work.

**Comment by ghassenBtb** [comment]
Yes, now it works, thank you :)

**Comment by miuros** [comment]
Hi, is there possible to update this download link, now it is unavailable again :)

**Comment by wdqin** [comment]
> Hi, is it possible to update this download link, now it is unavailable again :)

The school has changed its policy with Google Drive storage limit so I can't put it in the Drive anymore. I am working with our department and see if there's a more consistent place I can put these files again :(

**Comment by wang-weishi** [comment]
Thank you for the efforts of sharing this dataset, may I ask one question, are there any other possible ways to download this dataset?

**Comment by wdqin** [comment]
> Thank you for the efforts of sharing this dataset, may I ask one question, are there any other possible ways to download this dataset?

Hi all,

The link is updated thanks to Randa, I will upload the full version shortly.

Wenda

**Comment by wdqin** [comment]
Hi all,

The link has been updated and now you should be able to access all data uploaded before. I'm sorry for the inconvenience.
